#!/usr/bin/python
import time, os, random, datetime
from twisted.internet import reactor
from rdfaction import RoomAction
from louie import dispatcher

from speak import say

import hubclient
hubclient.connect()


def listen():
    print "i got response"
dispatcher.connect(listen, "timed test response")

def randomLine(filename):
    return random.choice([line.strip()
                          for line in open(filename).readlines()
                          if line.strip()])

class EveningLights:

    # you have to get from motion=yes to the door within this time, or
    # else I'll think you're someone coming home
    MOTION_TO_DOOR_SECONDS = 30
    
    def __init__(self):
        dispatcher.connect(self.door, "door")
        dispatcher.connect(self.motion, "motion")

        self.lastSeenInside = 0

    def door(self, state):
        print "door", state
        if state == "open":
            if self.lastSeenInside > time.time() - self.MOTION_TO_DOOR_SECONDS:
                print "bye"
                say(randomLine("evening_lights.goodbye.lines"))
            else:
                print "hello"
                say(randomLine("evening_lights.hello.lines"))
                if 18 <= datetime.datetime.now().hour <= 24:
                    RoomAction().fire_action("http://projects.bigasterisk.com/room/comeHome")
                              
            self.lastSeenInside = time.time()
                
    def motion(self, state):
        print "motion", state
        if state == "yes":
            self.lastSeenInside = time.time()


e = EveningLights()
say("evening lights program activated")

reactor.run()
