#!/usr/bin/python
import time, os, random, datetime
from twisted.internet import reactor
from rdfaction import RoomAction
from louie import dispatcher

from speak import say

import hubclient
hubclient.connect()


def listen():
    print "i got response"
dispatcher.connect(listen, "timed test response")

def randomLine(filename):
    return random.choice(
        [line.strip()
         for line in open("/my/proj/room/%s" % filename).readlines()
         if line.strip()])

class EveningLights:

    # you have to get from motion=yes to the door within this time, or
    # else I'll think you're someone coming home
    MOTION_TO_DOOR_SECONDS = 30

    # a second event this close to a first event is ignored (seconds)
    DEBOUNCE = 10
    
    def __init__(self):
        dispatcher.connect(self.door, "door")
        dispatcher.connect(self.motion, "motion")

        self.lastSeenInside = 0
        self.lastEvent = None

    def door(self, state):
        print "door", state
        now = time.time()
        if state == "open":
            if now - self.DEBOUNCE < self.lastEvent:
                return
            self.lastEvent = now
            if self.lastSeenInside > now - self.MOTION_TO_DOOR_SECONDS:
                print "bye"
                say(randomLine("evening_lights.goodbye.lines"))
            else:
                print "hello"
                if 18 <= datetime.datetime.now().hour <= 24:
                    RoomAction().fire_action("http://projects.bigasterisk.com/room/comeHome")
                say(randomLine("evening_lights.hello.lines"))
                              
            self.lastSeenInside = now
                
    def motion(self, state):
        print "motion", state
        if state == "yes":
            self.lastSeenInside = time.time()


e = EveningLights()
say("evening lights program activated")

reactor.run()
