#!/usr/local/bin/python

""" run 'lircd -n', don't bother with .lircrc, and then run this. lircd
commands will be used as room/ir/command actions"""

from logsetup import commonlogsetup
from twisted.internet import reactor, tksupport, defer, protocol
from twisted.protocols.basic import LineReceiver

import pygame

from rdfaction import RoomAction
log = commonlogsetup(filename=None)

room_action = RoomAction()
pygame.mixer.init()


class LircClient(LineReceiver):
    delimiter = "\n"
    def __init__(self):
        self.lastKey = None
        self.lastRep = None

        self.repeatingKeys = "volumedown volumeup".split()

        try:
            self.sound = pygame.mixer.Sound("/home/drewp/snd/angel_ogg/angel_question.wav")
        except pygame.error, e:
            log.warn("sound load failed: %s" % e)
            self.sound = None
        
    def lineReceived(self, line):
        hexcode, rep, key, device = line.split()
        rep = int(rep, 16)

        repeat = False
        if key == self.lastKey and rep > self.lastRep:
            repeat = True

        self.lastKey, self.lastRep = key, rep

        if repeat and key not in self.repeatingKeys:
            return

        if self.sound:
            self.sound.play()

        try:
            matches = room_action.fire(
                "<http://projects.bigasterisk.com/room/ir/command>",
                '"%s"' % key)
            if matches == 0:
                self.sound
        except (Exception, ), e:
            log.warn("action failed: %s" % e)
            pass

sock = "/dev/lircd"
protocol.ClientCreator(reactor, LircClient).connectUNIX(sock)
log.info("listening for commands on %s" % sock)
reactor.run()
